const RAW_PUBLISHERS = [
  ['8COUPONS', '8coupons'],
  ['AMAZONALEXA', 'Amazon Alexa'],
  ['AMERICANEXPRESS', 'American Express'],
  ['APPLE', 'Apple'],
  ['AROUNDME', 'AroundMe'],
  ['BETTERBUSINESSBUREAU', 'Better Business Bureau'],
  ['BING', 'Bing'],
  ['BRAVE', 'Brave'],
  ['BROWNBOOKNET', 'Brownbook.net'],
  ['CENTRALINDEXUS', 'Central Index US'],
  ['CHAMBEROFCOMMERCECOM', 'ChamberofCommerce.com'],
  ['CITYSEARCH', 'CitySearch'],
  ['CITYSQUARES', 'CitySquares'],
  ['CYLEX', 'Cylex'],
  ['DEXKNOWS', 'DexKnows'],
  ['DOLA', 'Dola'],
  ['DOORDASH', 'DoorDash'],
  ['DUNBRADSTREET', 'Dun & Bradstreet'],
  ['EZLOCAL', 'EZlocal'],
  ['FACEBOOK', 'Facebook'],
  ['FINDOPEN', 'Find Open'],
  ['FOURSQUARE', 'Foursquare'],
  ['GEMINI', 'Gemini'],
  ['GOLOCAL247', 'GoLocal247'],
  ['GOOGLEBUSINESSPROFILE', 'Google Business Profile'],
  ['HERE', 'HERE'],
  ['HOTFROG', 'HotFrog'],
  ['HOURSCOM', 'Hours.com'],
  ['INSIDERPAGES', 'Insider Pages'],
  ['INSTACART', 'Instacart'],
  ['INSTAGRAM', 'Instagram'],
  ['MAPQUEST', 'MapQuest'],
  ['MAPBOX', 'Mapbox'],
  ['MAPSTR', 'Mapstr'],
  ['MERCHANTCIRCLE', 'MerchantCircle'],
  ['METAPLACESGRAPH', 'Meta Places Graph'],
  ['MONEYMAILER', 'Money Mailer'],
  ['MYLOCALSERVICES', 'My Local Services'],
  ['NAVMII', 'Navmii'],
  ['NEXTDOOR', 'Nextdoor'],
  ['OPENAI', 'OpenAI'],
  ['OPENDI', 'Opendi'],
  ['PITNEYBOWES', 'Pitney Bowes'],
  ['POSTMATES', 'Postmates'],
  ['PROPERTYCAPSULE', 'Property Capsule'],
  ['SAFEGRAPH', 'SafeGraph'],
  ['SHOWMELOCAL', 'ShowMeLocal'],
  ['SIRI', 'Siri'],
  ['SNAPCHAT', 'Snapchat'],
  ['SOLEO', 'Soleo'],
  ['SPALOCAL', 'SpaLocal'],
  ['SUPERPAGES', 'Superpages'],
  ['TIKTOK', 'TikTok'],
  ['TOMTOM', 'TomTom'],
  ['TRIPADVISOR', 'TripAdvisor'],
  ['TUPALO', 'Tupalo'],
  ['USCITYNET', 'USCity.net'],
  ['UBER', 'Uber'],
  ['UBEREATS', 'Uber Eats'],
  ['UBERFREIGHT', 'Uber Freight'],
  ['WAZE', 'Waze'],
  ['WHERETO', 'Where To?'],
  ['YPCOM', 'YP.com'],
  ['YAHOO', 'Yahoo!'],
  ['YANDEX', 'Yandex'],
  ['YANGO', 'Yango'],
  ['YELLOWPAGESDIRECTORY', 'YellowPagesDirectory'],
  ['YELP', 'Yelp'],
  ['ZIPLOCALONLINE', 'ZipLocalOnline'],
  ['ELOCAL', 'eLocal'],
  ['IBEGIN', 'iBegin'],
  ['IGLOBAL', 'iGlobal'],
  ['N49', 'n49'],
  ['TELLOWS', 'tellows'],
]

const DIRECT_API_IDS = new Set(['GOOGLEBUSINESSPROFILE', 'BING', 'APPLE', 'FACEBOOK'])
const PARTNER_IDS = new Set([
  'YELP',
  'TRIPADVISOR',
  'UBER',
  'UBEREATS',
  'DOORDASH',
  'INSTAGRAM',
  'NEXTDOOR',
])
const DERIVED_IDS = new Set(['SIRI', 'WAZE', 'GEMINI', 'OPENAI', 'AMAZONALEXA', 'BRAVE'])

export const LISTINGS_PUBLISHER_CATALOG = RAW_PUBLISHERS.map(([id, name]) => ({
  id,
  name,
  pushMode: DIRECT_API_IDS.has(id)
    ? 'direct_api'
    : PARTNER_IDS.has(id)
      ? 'partner_api'
      : DERIVED_IDS.has(id)
        ? 'derived_visibility'
        : 'manual_or_monitor',
}))

export const buildListingsPublishers = (siteHost) =>
  LISTINGS_PUBLISHER_CATALOG.map((publisher) => ({
    id: publisher.id,
    name: publisher.name,
    pushMode: publisher.pushMode,
    status: 'not synced',
    accuracy: '0%',
    liveListings: 0,
    totalListings: 2,
    lastSynced: 'Never',
    liveUrl: `https://${siteHost}`,
  }))
